pre-commit hook to prevent commiting to develop or main

diff --git a/.scripts/pre-commit b/.scripts/pre-commit
--- a/.scripts/pre-commit
+++ b/.scripts/pre-commit
@@ -31,3 +31,31 @@ else
     #Exit
     exit 1
 fi
+
+# Branch
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+echo ""
+echo "Current Branch: $branch"
+echo ""
+
+if [ "$branch" = "develop" ]; then
+  echo "You can't commit directly to the $branch branch"
+  exit 1
+fi
+
+echo "You can commit directly to the $branch branch"
+
+# Branch
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+echo ""
+echo "Current Branch: $branch"
+echo ""
+
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to the $branch branch"
+  exit 1
+fi
+
+echo "You can commit directly to the $branch branch"
